### ISSUE TITLE
How to build using fake?

### ISSUE THREAD

**Issue by JohanLarsson** [mathnet/mathnet-spatial#9]
I have managed to build packages using:
Command: $(SolutionDir)build.cmd
Argumants: NuGet all
Initial directory: $(SolutionDir)

Question is what needs to be changed and where before building.
Assembly version is written in a bunch of places. Is RELEASENOTES.md the origin?

**Comment by cdrnet** [comment]
Yes, the fake build interprets the release notes to build version information, and propagates it to the assembly info files (this is intentional, and committed to the repo on official releases). So if you would like to make a new (local) release, update the release notes first and then launch the fake build with "All release" (or "NuGet release" if you only want the NuGet packages). It will put the artifacts to the out folder but won't try to publish anything remotely.

In Numerics this is documented in [maintaining.md](https://github.com/mathnet/mathnet-numerics/blob/master/MAINTAINING.md), this should be documented here as well.

**Comment by cdrnet** [comment]
Documented [here](http://spatial.mathdotnet.com/Build.html)
